name: views_weebi
version: 0.0.5
homepage: http://weebi.com/
description: views and widgets
#publish_to: none #https://onepub.dev/api/xnxpsdavuh/

environment: 
  sdk: '>=2.19.6 <3.0.0' #'>=2.7.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: flutter
  collection: ^1.14.12
  font_awesome_flutter: ^10.1.0 #icons 
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.1
  provider: ^6.0.3
  rc_router2: ^1.0.3
  flutter_typeahead: ^4.0.0
  flutter_styled_toast: ^2.1.3 #1.5.2+3 

  models_weebi: #^1.0.13
    path: ../models
  mixins_weebi: #^0.0.9
    path: ../mixins

dev_dependencies:
  flutter_test: 
    sdk: flutter
    #  flutter_lints: ^1.0.4 #^2.0.0
flutter: null
