name: views_weebi
version: 0.0.3
homepage: http://weebi.com/
publish_to: https://onepub.dev/api/xnxpsdavuh/
description: views and widgets

environment: 
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: flutter
  collection: ^1.15.0
  font_awesome_flutter: ^10.1.0
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.1
  provider: ^6.0.3
  rc_router2: ^1.0.0
  flutter_typeahead: 3.1.0 #4.0.0
  models_weebi:
    path: ../models_weebi 
    #hosted:
    #  url: https://onepub.dev/api/xnxpsdavuh/
    #  name: models_weebi
    #version: ^1.0.11
  mixins_weebi:
    path: ../mixins_weebi
    #hosted:
    #  url: https://onepub.dev/api/xnxpsdavuh/
    #  name: mixins_weebi
    #version: ^0.0.7
  closing:
    path: ../closing
    #hosted:
    #  url: https://onepub.dev/api/xnxpsdavuh/
    #  name: closing
    #version: ^1.0.7
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: null
